[build-system]
requires = ["poetry-core", "setuptools", "wheel"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "SciPhi"
version = "0.1.0"
description = "SciPhi: A framework for breaking scaling laws."
authors = ["Owen Colegrove <owen@emergentagi.com>"]
license = "Apache-2.0"
readme = "README.md"

[tool.poetry.dependencies]
# Required dependencies
numpy = "^1.26.0"
python = ">=3.10,<3.12"
python-dotenv = "^1.0.0"
pandas = "^2.1.0"
# Begin optional dependencies
# anthropic
anthropic = { version = "^0.3.10", optional = true }
# hf
accelerate = { version = "^0.23.0", optional = true }
datasets = { version = "^2.14.5", optional = true }
torch = { version = "^2.0.1", optional = true }
transformers = { version = "^4.33.1", optional = true }
# openai
openai = { version = "0.27.8", optional = true }
matplotlib = {version = "^3.8.0", optional = true}
plotly = {version = "^5.17.0", optional = true}
scipy = {version = "^1.11.2", optional = true}
scikit-learn = {version = "^1.3.1", optional = true}
# vllm
vllm = { version = "0.1.7", optional = true }
# llama-index
llama-index = { version = "^0.8.29.post1", optional = true }
# chroma
chromadb =  { version = "^0.4.12", optional = true }
retrying = "^1.3.4"
# llama-cpp
requests = {version = "2.31.0", optional = true}

[tool.poetry.extras]
anthropic_support = ["anthropic"]
hf_support = ["accelerate", "datasets", "torch", "transformers"]
openai_support = ["openai"]
openai_utils_support = ["openai"]
vllm_support = ["accelerate", "torch", "vllm"]
llama_index_support = ["llama-index"]
chroma_support = ["chromadb"]
llamacpp_support = ["requests"]
# omit "accelerate" and "vllm", since it can cause failures w/out cuda
all = ["anthropic", "datasets", "torch", "transformers", "openai", "matplotlib", "plotly", "scipy", "scikit-learn", "llama-index", "chromadb", "requests"]
all_with_cuda = ["anthropic", "accelerate" , "datasets", "torch", "transformers", "openai", "matplotlib", "plotly", "scipy", "scikit-learn", "llama-index", "chromadb", "vllm", "requests"]

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
flake8 = "6.1.0"
isort = "5.12.0"
pre-commit = "^3.3.3"
mypy = "^1.5.1"
sourcery = "^1.6.0"
types-requests = "^2.31.0.2"
types-attrs = "^19.1.0"
yapf = "0.40.1"

[tool.black]
line-length = 79

[tool.mypy]
ignore_missing_imports = true
exclude = 'playground/.*'

[[tool.mypy.overrides]]
module = "yaml"
ignore_missing_imports = true

[tool.flake8]
ignore = ["E501", "W503"]
exclude = 'playground/.*'

